# Generated by Django 4.2.7 on 2023-11-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastre',
            name='external_response',
            field=models.CharField(max_length=5),
        ),
    ]
