# Generated by Django 4.2.7 on 2023-11-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0002_alter_cadastre_external_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastre',
            old_name='cadstre_number',
            new_name='cadastre_number',
        ),
    ]
